Meteor.startup ->
#  IrregularVerb.remove({})
  if IrregularVerb.find({}).fetch().length is 0
    irregularVerb = [
      base : ['abide']
      pastSimple : ['abode', 'abided']
      pastParticiple : ['abode', 'abided', 'abidden']
      personSingular3rd : ['abides']
      presentParticiple : ['abiding']
    ,
      base : ['alight']
      pastSimple : ['alit', 'alighted']
      pastParticiple : ['alit', 'alighted']
      personSingular3rd : ['alights']
      presentParticiple : ['alighting']
    ,
      base : ['arise']
      pastSimple : ['arose']
      pastParticiple : ['arisen']
      personSingular3rd : ['arises']
      presentParticiple : ['arising']
    ,
      base : ['awake']
      pastSimple : ['awoke']
      pastParticiple : ['awoken']
      personSingular3rd : ['awakes']
      presentParticiple : ['awaking']
    ,
      base : ['be']
      pastSimple : ['was', 'were']
      pastParticiple : ['bee']
      personSingular3rd : ['is', 'am', 'are']
      presentParticiple : ['being']
    ,
      base : ['bear']
      pastSimple : ['born']
      pastParticiple : ['born', 'borne']
      personSingular3rd : ['bears']
      presentParticiple : ['bearing']
    ,
      base : ['beat']
      pastSimple : ['beat']
      pastParticiple : ['beaten']
      personSingular3rd : ['beats']
      presentParticiple : ['beating']
    ,
      base : ['become']
      pastSimple : ['became']
      pastParticiple : ['become']
      personSingular3rd : ['becomes']
      presentParticiple : ['becoming']
    ,
      base : ['begin']
      pastSimple : ['began']
      pastParticiple : ['begun']
      personSingular3rd : ['begins']
      presentParticiple : ['beginning']
    ,
      base : ['behold']
      pastSimple : ['beheld']
      pastParticiple : ['behold']
      personSingular3rd : ['beholds']
      presentParticiple : ['beholding']
    ,
      base : ['bend']
      pastSimple : ['bent']
      pastParticiple : ['bent']
      personSingular3rd : ['bends']
      presentParticiple : ['bending']
    ,
      base : ['bet']
      pastSimple : ['bet']
      pastParticiple : ['bet']
      personSingular3rd : ['bets']
      presentParticiple : ['betting']
    ,
      base : ['bid']
      pastSimple : ['bade']
      pastParticiple : ['bidden']
      personSingular3rd : ['bids']
      presentParticiple : ['bidding']
    ,
      base : ['bid']
      pastSimple : ['bid']
      pastParticiple : ['bid']
      personSingular3rd : ['bids']
      presentParticiple : ['bidding']
    ,
      base : ['bind']
      pastSimple : ['bound']
      pastParticiple : ['bound']
      personSingular3rd : ['binds']
      presentParticiple : ['binding']
    ,
      base : ['bite']
      pastSimple : ['bit']
      pastParticiple : ['bitten']
      personSingular3rd : ['bites']
      presentParticiple : ['biting']
    ,
      base : ['bleed']
      pastSimple : ['bled']
      pastParticiple : ['bled']
      personSingular3rd : ['bleeds']
      presentParticiple : ['bleeding']
    ,
      base : ['bring']
      pastSimple : ['brought']
      pastParticiple : ['brought']
      personSingular3rd : ['brings']
      presentParticiple : ['bringing']
    ,
      base : ['broadcast']
      pastSimple : ['broadcast', 'broadcasted']
      pastParticiple : ['broadcast', 'broadcasted']
      personSingular3rd : ['broadcasts']
      presentParticiple : ['broadcasting']
    ,
      base : ['build']
      pastSimple : ['built']
      pastParticiple : ['built']
      personSingular3rd : ['builds']
      presentParticiple : ['building']
    ,
      base : ['burn']
      pastSimple : ['burnt', 'burned']
      pastParticiple : ['burnt', 'burned']
      personSingular3rd : ['burns']
      presentParticiple : ['burning']
    ,
      base : ['burst']
      pastSimple : ['burst']
      pastParticiple : ['burst']
      personSingular3rd : ['bursts']
      presentParticiple : ['bursting']
    ,
      base : ['buy']
      pastSimple : ['bought']
      pastParticiple : ['bought']
      personSingular3rd : ['buys']
      presentParticiple : ['buying']
    ,
      base : ['cast']
      pastSimple : ['cast']
      pastParticiple : ['cast']
      personSingular3rd : ['casts']
      presentParticiple : ['casting']
    ,
      base : ['catch']
      pastSimple : ['caught']
      pastParticiple : ['caught']
      personSingular3rd : ['catches']
      presentParticiple : ['catching']
    ,
      base : ['choose']
      pastSimple : ['choise']
      pastParticiple : ['choosen']
      personSingular3rd : ['chooses']
      presentParticiple : ['choosing']
    ,
      base : ['clap']
      pastSimple : ['calpt', 'clapped']
      pastParticiple : ['clapt', 'clapped']
      personSingular3rd : ['claps']
      presentParticiple : ['clapping']
    ,
      base : ['cling']
      pastSimple : ['clung']
      pastParticiple : ['clung']
      personSingular3rd : ['clings']
      presentParticiple : ['clinging']
    ,
      base : ['clothe']
      pastSimple : ['clad', 'clothed']
      pastParticiple : ['clad', 'clothed']
      personSingular3rd : ['clothes']
      presentParticiple : ['clothing']
    ,
      base : ['come']
      pastSimple : ['came']
      pastParticiple : ['come']
      personSingular3rd : ['comes']
      presentParticiple : ['coming']
    ,
      base : ['cost']
      pastSimple : ['cost']
      pastParticiple : ['cost']
      personSingular3rd : ['costs']
      presentParticiple : ['costing']
    ,
      base : ['creep']
      pastSimple : ['crept']
      pastParticiple : ['crept']
      personSingular3rd : ['creeps']
      presentParticiple : ['creeping']
    ,
      base : ['cut']
      pastSimple : ['cut']
      pastParticiple : ['cut']
      personSingular3rd : ['cuts']
      presentParticiple : ['cutting']
    ,
      base : ['dare']
      pastSimple : ['dared', 'durst']
      pastParticiple : ['dared']
      personSingular3rd : ['dares']
      presentParticiple : ['daring']
    ,
      base : ['deal']
      pastSimple : ['dealt']
      pastParticiple : ['dealt']
      personSingular3rd : ['deals']
      presentParticiple : ['dealing']
    ,
      base : ['dig']
      pastSimple : ['dug']
      pastParticiple : ['dug']
      personSingular3rd : ['digs']
      presentParticiple : ['digging']
    ,
      base : ['dive']
      pastSimple : ['dove', 'dived']
      pastParticiple : ['dived']
      personSingular3rd : ['dives']
      presentParticiple : ['diving']
    ,
      base : ['do']
      pastSimple : ['did']
      pastParticiple : ['done']
      personSingular3rd : ['does']
      presentParticiple : ['doing']
    ,
      base : ['draw']
      pastSimple : ['drew']
      pastParticiple : ['drawn']
      personSingular3rd : ['draws']
      presentParticiple : ['drawing']
    ,
      base : ['dream']
      pastSimple : ['dreamt', 'dreamed']
      pastParticiple : ['dream', 'dreamed']
      personSingular3rd : ['dreams']
      presentParticiple : ['dreaming']
    ,
      base : ['drink']
      pastSimple : ['drank']
      pastParticiple : ['drunk']
      personSingular3rd : ['drinks']
      presentParticiple : ['drinking']
    ,
      base : ['drive']
      pastSimple : ['drove']
      pastParticiple : ['driven']
      personSingular3rd : ['drives']
      presentParticiple : ['driving']
    ,
      base : ['dwell']
      pastSimple : ['dwelt']
      pastParticiple : ['dwelt']
      personSingular3rd : ['dwells']
      presentParticiple : ['dwelling']
    ,
      base : ['eat']
      pastSimple : ['ate']
      pastParticiple : ['eatten']
      personSingular3rd : ['eats']
      presentParticiple : ['eating']
    ,
      base : ['fall']
      pastSimple : ['fell']
      pastParticiple : ['fallen']
      personSingular3rd : ['falls']
      presentParticiple : ['falling']
    ,
      base : ['feed']
      pastSimple : ['fed']
      pastParticiple : ['fed']
      personSingular3rd : ['feeds']
      presentParticiple : ['feeding']
    ,
      base : ['Feel']
      pastSimple : ['Felt']
      pastParticiple : ['Felt']
      personSingular3rd : ['Feels']
      presentParticiple : ['Feeling']
    ,
      base : ['Fight']
      pastSimple : ['Fought']
      pastParticiple : ['Fought']
      personSingular3rd : ['Fights']
      presentParticiple : ['Fighting']
    ,
      base : ['Find']
      pastSimple : ['Found']
      pastParticiple : ['Found']
      personSingular3rd : ['Finds']
      presentParticiple : ['Finding']
    ,
      base : ['Fit']
      pastSimple : ['Fit', 'Fitted']
      pastParticiple : ['Fit', 'Fitted']
      personSingular3rd : ['Fits']
      presentParticiple : ['Fitting']
    ,
      base : ['Flee']
      pastSimple : ['Fled']
      pastParticiple : ['Fled']
      personSingular3rd : ['Flees']
      presentParticiple : ['Fleeing']
    ,
      base : ['Fling']
      pastSimple : ['Flung']
      pastParticiple : ['Flung']
      personSingular3rd : ['Flings']
      presentParticiple : ['Flinging']
    ,
      base : ['Fly']
      pastSimple : ['Flew']
      pastParticiple : ['Flown']
      personSingular3rd : ['Flies']
      presentParticiple : ['Flying']
    ,
      base : ['Forbid']
      pastSimple : ['Forbade', 'Forbad']
      pastParticiple : ['Forbidden']
      personSingular3rd : ['Forbids']
      presentParticiple : ['Forbidding']
    ,
      base : ['Forecast']
      pastSimple : ['Forecast', 'Forecasted']
      pastParticiple : ['Forecast', 'Forecasted']
      personSingular3rd : ['Forecasts']
      presentParticiple : ['Forecasting']
    ,
      base : ['Foresee']
      pastSimple : ['Foresaw']
      pastParticiple : ['Foreseen']
      personSingular3rd : ['Foresees']
      presentParticiple : ['Foreseeing']
    ,
      base : ['Foretell']
      pastSimple : ['Foretold']
      pastParticiple : ['Foretold']
      personSingular3rd : ['Foretells']
      presentParticiple : ['Foretelling']
    ,
      base : ['Forget']
      pastSimple : ['Forgot']
      pastParticiple : ['Forgotten']
      personSingular3rd : ['Forgets']
      presentParticiple : ['Foregetting']
    ,
      base : ['Forgive']
      pastSimple : ['Forgave']
      pastParticiple : ['Forgiven']
      personSingular3rd : ['Forgives']
      presentParticiple : ['Forgiving']
    ,
      base : ['Forsake']
      pastSimple : ['Forsook']
      pastParticiple : ['Forsaken']
      personSingular3rd : ['Forsakes']
      presentParticiple : ['Forsaking']
    ,
      base : ['Freeze']
      pastSimple : ['Froze']
      pastParticiple : ['Frozen']
      personSingular3rd : ['Freezes']
      presentParticiple : ['Freezing']
    ,
      base : ['Frostbite']
      pastSimple : ['Frostbit']
      pastParticiple : ['Frostbitten']
      personSingular3rd : ['Frostbites']
      presentParticiple : ['Frostbiting']
    ,
      base : ['Get']
      pastSimple : ['Got']
      pastParticiple : ['Got', 'Gotten']
      personSingular3rd : ['Gets']
      presentParticiple : ['Getting']
    ,
      base : ['Give']
      pastSimple : ['Gave']
      pastParticiple : ['Given']
      personSingular3rd : ['Gives']
      presentParticiple : ['Giving']
    ,
      base : ['Go']
      pastSimple : ['Went']
      pastParticiple : ['Gone', 'Been']
      personSingular3rd : ['Goes']
      presentParticiple : ['Going']
    ,
      base : ['Grind']
      pastSimple : ['Ground']
      pastParticiple : ['Ground']
      personSingular3rd : ['Grinds']
      presentParticiple : ['Grinding']
    ,
      base : ['Grow']
      pastSimple : ['Grew']
      pastParticiple : ['Grown']
      personSingular3rd : ['Grows']
      presentParticiple : ['Growing']
    ,
      base : ['Handwrite']
      pastSimple : ['Handwrote']
      pastParticiple : ['Handwritten']
      personSingular3rd : ['Handwrites']
      presentParticiple : ['Handwriting']
    ,
      base : ['Hang']
      pastSimple : ['Hung', 'Hanged']
      pastParticiple : ['Hung', 'Hanged']
      personSingular3rd : ['Hangs']
      presentParticiple : ['Hanging']
    ,
      base : ['Have']
      pastSimple : ['Had']
      pastParticiple : ['Had']
      personSingular3rd : ['Has']
      presentParticiple : ['Having']
    ,
      base : ['Hear']
      pastSimple : ['Heard']
      pastParticiple : ['Heard']
      personSingular3rd : ['Hears']
      presentParticiple : ['Hearing']
    ,
      base : ['Hide']
      pastSimple : ['Hid']
      pastParticiple : ['Hidden']
      personSingular3rd : ['Hides']
      presentParticiple : ['Hiding']
    ,
      base : ['Hit']
      pastSimple : ['Hit']
      pastParticiple : ['Hit']
      personSingular3rd : ['Hits']
      presentParticiple : ['Hitting']
    ,
      base : ['Hold']
      pastSimple : ['Held']
      pastParticiple : ['Held']
      personSingular3rd : ['Holds']
      presentParticiple : ['Holding']
    ,
      base : ['Hurt']
      pastSimple : ['Hurt']
      pastParticiple : ['Hurt']
      personSingular3rd : ['Hurts']
      presentParticiple : ['Hurting']
    ,
      base : ['Inlay']
      pastSimple : ['Inlaid']
      pastParticiple : ['Inlaid']
      personSingular3rd : ['Inlays']
      presentParticiple : ['Inlaying']
    ,
      base : ['Input']
      pastSimple : ['Input', 'Inputted']
      pastParticiple : ['Input', 'Inputted']
      personSingular3rd : ['Inputs']
      presentParticiple : ['Inputting']
    ,
      base : ['Interlay']
      pastSimple : ['Interlaid']
      pastParticiple : ['Interlaid']
      personSingular3rd : ['Interlays']
      presentParticiple : ['Interlaying']
    ,
      base : ['Keep']
      pastSimple : ['Kept']
      pastParticiple : ['Kept']
      personSingular3rd : ['Keeps']
      presentParticiple : ['Keeping']
    ,
      base : ['Kneel']
      pastSimple : ['Knelt', 'Kneeled']
      pastParticiple : ['Knelt', 'Kneeled']
      personSingular3rd : ['Kneels']
      presentParticiple : ['Kneeling']
    ,
      base : ['Knit']
      pastSimple : ['Knit', 'Knitted']
      pastParticiple : ['Knit', 'Knitted']
      personSingular3rd : ['Knits']
      presentParticiple : ['Knitting']
    ,
      base : ['Know']
      pastSimple : ['Knew']
      pastParticiple : ['Known']
      personSingular3rd : ['Knows']
      presentParticiple : ['Knowing']
    ,
      base : ['Lay']
      pastSimple : ['Laid']
      pastParticiple : ['Laid']
      personSingular3rd : ['Lays']
      presentParticiple : ['laying']
    ,
      base : ['Lead']
      pastSimple : ['Led']
      pastParticiple : ['Led']
      personSingular3rd : ['Leads']
      presentParticiple : ['Leading']
    ,
      base : ['Lean']
      pastSimple : ['Leant', 'Leaned']
      pastParticiple : ['Leant', 'Leaned']
      personSingular3rd : ['Leans']
      presentParticiple : ['Leaning']
    ,
      base : ['Leap']
      pastSimple : ['Leapt', 'Leaped']
      pastParticiple : ['Leapt', 'Leaped']
      personSingular3rd : ['Leaps']
      presentParticiple : ['Leaping']
    ,
      base : ['Learn']
      pastSimple : ['Learnt', 'Learned']
      pastParticiple : ['Learnt', 'Learned']
      personSingular3rd : ['Learns']
      presentParticiple : ['Learning']
    ,
      base : ['Leave']
      pastSimple : ['Left']
      pastParticiple : ['Left']
      personSingular3rd : ['Leaves']
      presentParticiple : ['Leaving']
    ,
      base : ['Lend']
      pastSimple : ['Lent']
      pastParticiple : ['Lent']
      personSingular3rd : ['Lends']
      presentParticiple : ['Lending']
    ,
      base : ['Let']
      pastSimple : ['Let']
      pastParticiple : ['Let']
      personSingular3rd : ['Lets']
      presentParticiple : ['Letting']
    ,
      base : ['Lie']
      pastSimple : ['Lay']
      pastParticiple : ['Lain']
      personSingular3rd : ['Lies']
      presentParticiple : ['Lying']
    ,
      base : ['Light']
      pastSimple : ['Lit']
      pastParticiple : ['Lit']
      personSingular3rd : ['Lights']
      presentParticiple : ['Lighting']
    ,
      base : ['Lose']
      pastSimple : ['Lost']
      pastParticiple : ['Lost']
      personSingular3rd : ['Loses']
      presentParticiple : ['Losing']
    ,
      base : ['Make']
      pastSimple : ['Made']
      pastParticiple : ['Made']
      personSingular3rd : ['Makes']
      presentParticiple : ['Making']
    ,
      base : ['Mean']
      pastSimple : ['Meant']
      pastParticiple : ['Meant']
      personSingular3rd : ['Means']
      presentParticiple : ['Meaning']
    ,
      base : ['Meet']
      pastSimple : ['Met']
      pastParticiple : ['Met']
      personSingular3rd : ['Meets']
      presentParticiple : ['Meeting']
    ,
      base : ['Melt']
      pastSimple : ['Melted']
      pastParticiple : ['Molten', 'Melted']
      personSingular3rd : ['Melts']
      presentParticiple : ['Melting']
    ,
      base : ['Mislead']
      pastSimple : ['Misled']
      pastParticiple : ['Misled']
      personSingular3rd : ['Misleads']
      presentParticiple : ['Misleading']
    ,
      base : ['Mistake']
      pastSimple : ['Mistook']
      pastParticiple : ['Mistaken']
      personSingular3rd : ['Mistake']
      presentParticiple : ['Mistaking']
    ,
      base : ['Misunderstand']
      pastSimple : ['Misunderstood']
      pastParticiple : ['Misunderstood']
      personSingular3rd : ['Misunderstands']
      presentParticiple : ['Misunderstanding']
    ,
      base : ['Miswed']
      pastSimple : ['Miswed', 'Miswedded']
      pastParticiple : ['Miswed', 'Miswedded']
      personSingular3rd : ['Misweds']
      presentParticiple : ['Mis']
    ,
      base : ['Mow']
      pastSimple : ['Mowed']
      pastParticiple : ['Mown']
      personSingular3rd : ['Mows']
      presentParticiple : ['Mowing']
    ,
      base : ['Overdraw']
      pastSimple : ['Overdrew']
      pastParticiple : ['Overdrawn']
      personSingular3rd : ['Overdraws']
      presentParticiple : ['Overdrawing']
    ,
      base : ['Overhear']
      pastSimple : ['Overheard']
      pastParticiple : ['Overheard']
      personSingular3rd : ['Overhears']
      presentParticiple : ['Overhearing']
    ,
      base : ['Overtake']
      pastSimple : ['Overtook']
      pastParticiple : ['Overtaken']
      personSingular3rd : ['Overtakes']
      presentParticiple : ['Overtaking']
    ,
      base : ['Pay']
      pastSimple : ['Paid']
      pastParticiple : ['Paid']
      personSingular3rd : ['Pays']
      presentParticiple : ['Paying']
    ,
      base : ['Preset']
      pastSimple : ['Preset']
      pastParticiple : ['Preset']
      personSingular3rd : ['Prests']
      presentParticiple : ['Presetting']
    ,
      base : ['Prove']
      pastSimple : ['Proved']
      pastParticiple : ['Proven', 'Proved']
      personSingular3rd : ['Proves']
      presentParticiple : ['Proving']
    ,
      base : ['Put']
      pastSimple : ['Put']
      pastParticiple : ['Put']
      personSingular3rd : ['Puts']
      presentParticiple : ['Putting']
    ,
      base : ['Quit']
      pastSimple : ['Quit']
      pastParticiple : ['Quit']
      personSingular3rd : ['Quits']
      presentParticiple : ['Quitting']
    ,
      base : ['Re-prove']
      pastSimple : ['Re-proved']
      pastParticiple : ['Re-proven', 'Re-proved']
      personSingular3rd : ['Re-proves']
      presentParticiple : ['Re-proving']
    ,
      base : ['Read']
      pastSimple : ['Read']
      pastParticiple : ['Read']
      personSingular3rd : ['Reads']
      presentParticiple : ['Reading']
    ,
      base : ['Rid']
      pastSimple : ['Rid', 'Ridded']
      pastParticiple : ['Rid', 'Ridded']
      personSingular3rd : ['Rids']
      presentParticiple : ['Ridding']
    ,
      base : ['Ride']
      pastSimple : ['Rode']
      pastParticiple : ['Ridden']
      personSingular3rd : ['Rides']
      presentParticiple : ['Riding']
    ,
      base : ['Ring']
      pastSimple : ['Rang']
      pastParticiple : ['Rung']
      personSingular3rd : ['Rings']
      presentParticiple : ['Ringing']
    ,
      base : ['Rise']
      pastSimple : ['Rose']
      pastParticiple : ['Risen']
      personSingular3rd : ['Rises']
      presentParticiple : ['Rising']
    ,
      base : ['Rive']
      pastSimple : ['Rived']
      pastParticiple : ['Riven', 'Rived']
      personSingular3rd : ['Rives']
      presentParticiple : ['Riving']
    ,
      base : ['Run']
      pastSimple : ['Ran']
      pastParticiple : ['Run']
      personSingular3rd : ['Runs']
      presentParticiple : ['Running']
    ,
      base : ['Saw']
      pastSimple : ['Sawed']
      pastParticiple : ['Sawn', 'Sawed']
      personSingular3rd : ['saws']
      presentParticiple : ['sawing']
    ,
      base : ['Say']
      pastSimple : ['Said']
      pastParticiple : ['Said']
      personSingular3rd : ['Says']
      presentParticiple : ['Saying']
    ,
      base : ['See']
      pastSimple : ['Saw']
      pastParticiple : ['Seen']
      personSingular3rd : ['Sees']
      presentParticiple : ['Seeing']
    ,
      base : ['Seek']
      pastSimple : ['Sought']
      pastParticiple : ['Sought']
      personSingular3rd : ['Seeks']
      presentParticiple : ['Seeking']
    ,
      base : ['Sell']
      pastSimple : ['Sold']
      pastParticiple : ['Sold']
      personSingular3rd : ['Sells']
      presentParticiple : ['Selling']
    ,
      base : ['Send']
      pastSimple : ['Sent']
      pastParticiple : ['Sent']
      personSingular3rd : ['Sends']
      presentParticiple : ['Sending']
    ,
      base : ['Set']
      pastSimple : ['Set']
      pastParticiple : ['Set']
      personSingular3rd : ['Sets']
      presentParticiple : ['Setting']
    ,
      base : ['Sew']
      pastSimple : ['Sewed']
      pastParticiple : ['Sewn', 'swed']
      personSingular3rd : ['sews']
      presentParticiple : ['sewing']
    ,
      base : ['Shake']
      pastSimple : ['Shook']
      pastParticiple : ['Shaken']
      personSingular3rd : ['Shakes']
      presentParticiple : ['Shaking']
    ,
      base : ['Shave']
      pastSimple : ['Shaved']
      pastParticiple : ['Shaven', 'Shaved']
      personSingular3rd : ['Shaves']
      presentParticiple : ['Shaving']
    ,
      base : ['Shear']
      pastSimple : ['Shore', 'Sheared']
      pastParticiple : ['Shorn', 'Sheared']
      personSingular3rd : ['Shears']
      presentParticiple : ['Shearing']
    ,
      base : ['Shed']
      pastSimple : ['Shed']
      pastParticiple : ['Shed']
      personSingular3rd : ['Sheds']
      presentParticiple : ['Shedding']
    ,
      base : ['Shine']
      pastSimple : ['Shone']
      pastParticiple : ['Shone']
      personSingular3rd : ['Shines']
      presentParticiple : ['Shining']
    ,
      base : ['Shoe']
      pastSimple : ['Shod']
      pastParticiple : ['Shod']
      personSingular3rd : ['Shoes']
      presentParticiple : ['Shoeing']
    ,
      base : ['Shoot']
      pastSimple : ['Shot']
      pastParticiple : ['Shot']
      personSingular3rd : ['Shoots']
      presentParticiple : ['Shooting']
    ,
      base : ['Show']
      pastSimple : ['Showed']
      pastParticiple : ['Shown']
      personSingular3rd : ['Shows']
      presentParticiple : ['Showing']
    ,
      base : ['Shrink']
      pastSimple : ['Shrank']
      pastParticiple : ['Shrunk']
      personSingular3rd : ['Shrinks']
      presentParticiple : ['Shrinking']
    ,
      base : ['Shut']
      pastSimple : ['Shut']
      pastParticiple : ['Shut']
      personSingular3rd : ['Shuts']
      presentParticiple : ['Shutting']
    ,
      base : ['Sing']
      pastSimple : ['Sang']
      pastParticiple : ['Sung']
      personSingular3rd : ['Sings']
      presentParticiple : ['Singing']
    ,
      base : ['Sink']
      pastSimple : ['Sank']
      pastParticiple : ['Sunk']
      personSingular3rd : ['Sinks']
      presentParticiple : ['Sinking']
    ,
      base : ['Sit']
      pastSimple : ['Sat']
      pastParticiple : ['Sat']
      personSingular3rd : ['Sits']
      presentParticiple : ['Sitting']
    ,
      base : ['Slay']
      pastSimple : ['Slew']
      pastParticiple : ['Slain']
      personSingular3rd : ['Slays']
      presentParticiple : ['Slaying']
    ,
      base : ['Sleep']
      pastSimple : ['Slept']
      pastParticiple : ['Slept']
      personSingular3rd : ['Sleeps']
      presentParticiple : ['Sleeping']
    ,
      base : ['Slide']
      pastSimple : ['Slid']
      pastParticiple : ['Slid', 'Slidden']
      personSingular3rd : ['slides']
      presentParticiple : ['sliding']
    ,
      base : ['Sling']
      pastSimple : ['Slung']
      pastParticiple : ['Slung']
      personSingular3rd : ['Slings']
      presentParticiple : ['Slinging']
    ,
      base : ['Slink']
      pastSimple : ['Slunk']
      pastParticiple : ['Slunk']
      personSingular3rd : ['Slinks']
      presentParticiple : ['Slinking']
    ,
      base : ['Slit']
      pastSimple : ['Slit']
      pastParticiple : ['Slit']
      personSingular3rd : ['Slits']
      presentParticiple : ['Slitting']
    ,
      base : ['Smell']
      pastSimple : ['Smelt', 'Smelled']
      pastParticiple : ['Smelt', 'Smelled']
      personSingular3rd : ['Smells']
      presentParticiple : ['Smelling']
    ,
      base : ['Sneak']
      pastSimple : ['Sneaked', 'Snuck']
      pastParticiple : ['Sneaked', 'Snuck']
      personSingular3rd : ['Sneaks']
      presentParticiple : ['Sneaking']
    ,
      base : ['Soothsay']
      pastSimple : ['Soothsaid']
      pastParticiple : ['Soothsaid']
      personSingular3rd : ['Soothsays']
      presentParticiple : ['Soothsaying']
    ,
      base : ['Sow']
      pastSimple : ['Sowed']
      pastParticiple : ['Sown']
      personSingular3rd : ['Sows']
      presentParticiple : ['Sowing']
    ,
      base : ['Speak']
      pastSimple : ['Spoke']
      pastParticiple : ['Spoken']
      personSingular3rd : ['Speaks']
      presentParticiple : ['Speaking']
    ,
      base : ['Speed']
      pastSimple : ['Sped', 'Speeded']
      pastParticiple : ['Sped', 'Speeded']
      personSingular3rd : ['Speeds']
      presentParticiple : ['Speeding']
    ,
      base : ['Spell']
      pastSimple : ['Spelt', 'Spelled']
      pastParticiple : ['Spelt', 'Spelled']
      personSingular3rd : ['Spells']
      presentParticiple : ['Spelling']
    ,
      base : ['Spend']
      pastSimple : ['Spent']
      pastParticiple : ['Spent']
      personSingular3rd : ['Spends']
      presentParticiple : ['Spending']
    ,
      base : ['Spill']
      pastSimple : ['Spilt', 'Spilled']
      pastParticiple : ['Spilt', 'Spilled']
      personSingular3rd : ['Spills']
      presentParticiple : ['Spilling']
    ,
      base : ['Spin']
      pastSimple : ['Span', 'Spun']
      pastParticiple : ['Spun']
      personSingular3rd : ['Spins']
      presentParticiple : ['Spinning']
    ,
      base : ['Spit']
      pastSimple : ['Spat', 'Spit']
      pastParticiple : ['Spat', 'Spit']
      personSingular3rd : ['Spits']
      presentParticiple : ['Spitting']
    ,
      base : ['Split']
      pastSimple : ['Split']
      pastParticiple : ['Split']
      personSingular3rd : ['Splits']
      presentParticiple : ['Splitting']
    ,
      base : ['Spoil']
      pastSimple : ['Spoilt', 'Spoiled']
      pastParticiple : ['Spoilt', 'Spoiled']
      personSingular3rd : ['Spoils']
      presentParticiple : ['Spoiling']
    ,
      base : ['Spread']
      pastSimple : ['Spread']
      pastParticiple : ['Spread']
      personSingular3rd : ['Spreads']
      presentParticiple : ['Spreading']
    ,
      base : ['Spring']
      pastSimple : ['Sprang']
      pastParticiple : ['Sprung']
      personSingular3rd : ['Springs']
      presentParticiple : ['Springing']
    ,
      base : ['Stand']
      pastSimple : ['Stood']
      pastParticiple : ['Stood']
      personSingular3rd : ['Stands']
      presentParticiple : ['Standing']
    ,
      base : ['Steal']
      pastSimple : ['Stole']
      pastParticiple : ['Stolen']
      personSingular3rd : ['Steals']
      presentParticiple : ['Stealing']
    ,
      base : ['Stick']
      pastSimple : ['Stuck']
      pastParticiple : ['Stuck']
      personSingular3rd : ['Sticks']
      presentParticiple : ['Sticking']
    ,
      base : ['Sting']
      pastSimple : ['Stung']
      pastParticiple : ['Stung']
      personSingular3rd : ['Stings']
      presentParticiple : ['Stinging']
    ,
      base : ['Stink']
      pastSimple : ['Stank']
      pastParticiple : ['Stunk']
      personSingular3rd : ['Stinks']
      presentParticiple : ['Stinking']
    ,
      base : ['Stride']
      pastSimple : ['Strode/Strided']
      pastParticiple : ['Stridden']
      personSingular3rd : ['Strides']
      presentParticiple : ['Striding']
    ,
      base : ['Strike']
      pastSimple : ['Struck']
      pastParticiple : ['Struck/Stricken']
      personSingular3rd : ['Strikes']
      presentParticiple : ['Striking']
    ,
      base : ['String']
      pastSimple : ['Strung']
      pastParticiple : ['Strung']
      personSingular3rd : ['Strings']
      presentParticiple : ['Stringing']
    ,
      base : ['Strip']
      pastSimple : ['Stript/Stripped']
      pastParticiple : ['Stript/Stripped']
      personSingular3rd : ['Strips']
      presentParticiple : ['Stripping']
    ,
      base : ['Strive']
      pastSimple : ['Strove']
      pastParticiple : ['Striven']
      personSingular3rd : ['Strives']
      presentParticiple : ['Striving']
    ,
      base : ['Sublet']
      pastSimple : ['Sublet']
      pastParticiple : ['Sublet']
      personSingular3rd : ['Sublets']
      presentParticiple : ['Subletting']
    ,
      base : ['Sunburn']
      pastSimple : ['Sunburned/Sunburnt']
      pastParticiple : ['Sunburned/Sunburnt']
      personSingular3rd : ['Sunburns']
      presentParticiple : ['Sunburning']
    ,
      base : ['Swear']
      pastSimple : ['Swore']
      pastParticiple : ['Sworn']
      personSingular3rd : ['Swears']
      presentParticiple : ['Swearing']
    ,
      base : ['Sweat']
      pastSimple : ['Sweat/Sweated']
      pastParticiple : ['Sweat/Sweated']
      personSingular3rd : ['Sweats']
      presentParticiple : ['Sweating']
    ,
      base : ['Sweep']
      pastSimple : ['Swept/Sweeped']
      pastParticiple : ['Swept/Sweeped']
      personSingular3rd : ['Sweeps']
      presentParticiple : ['Sweeping']
    ,
      base : ['Swell']
      pastSimple : ['Swelled']
      pastParticiple : ['Swollen']
      personSingular3rd : ['Swells']
      presentParticiple : ['Swelling']
    ,
      base : ['Swim']
      pastSimple : ['Swam']
      pastParticiple : ['Swum']
      personSingular3rd : ['Swims']
      presentParticiple : ['Swimming']
    ,
      base : ['Swing']
      pastSimple : ['Swung']
      pastParticiple : ['Swung']
      personSingular3rd : ['Swings']
      presentParticiple : ['Swinging']
    ,
      base : ['Take']
      pastSimple : ['Took']
      pastParticiple : ['Taken']
      personSingular3rd : ['Takes']
      presentParticiple : ['Taking']
    ,
      base : ['Teach']
      pastSimple : ['Taught']
      pastParticiple : ['Taught']
      personSingular3rd : ['Teaches']
      presentParticiple : ['Teaching']
    ,
      base : ['Tear']
      pastSimple : ['Tore']
      pastParticiple : ['Torn']
      personSingular3rd : ['Tears']
      presentParticiple : ['Tearing']
    ,
      base : ['Tell']
      pastSimple : ['Told']
      pastParticiple : ['Told']
      personSingular3rd : ['Tells']
      presentParticiple : ['Telling']
    ,
      base : ['Think']
      pastSimple : ['Thought']
      pastParticiple : ['Thought']
      personSingular3rd : ['Thinks']
      presentParticiple : ['Thinking']
    ,
      base : ['Thrive']
      pastSimple : ['Throve/Thrived']
      pastParticiple : ['Thriven/Thrived']
      personSingular3rd : ['Thrives']
      presentParticiple : ['Thriving']
    ,
      base : ['Throw']
      pastSimple : ['Threw']
      pastParticiple : ['Thrown']
      personSingular3rd : ['Throws']
      presentParticiple : ['Throwing']
    ,
      base : ['Thrust']
      pastSimple : ['Thrust']
      pastParticiple : ['Thrust']
      personSingular3rd : ['Thrusts']
      presentParticiple : ['Thrusting']
    ,
      base : ['Tread']
      pastSimple : ['Trod']
      pastParticiple : ['Trodden']
      personSingular3rd : ['Treads']
      presentParticiple : ['Treading']
    ,
      base : ['Undergo']
      pastSimple : ['Underwent']
      pastParticiple : ['Undergone']
      personSingular3rd : ['Undergoes']
      presentParticiple : ['Undergoing']
    ,
      base : ['Understand']
      pastSimple : ['Understood']
      pastParticiple : ['Understood']
      personSingular3rd : ['Understands']
      presentParticiple : ['Understanding']
    ,
      base : ['Undertake']
      pastSimple : ['Undertook']
      pastParticiple : ['Undertaken']
      personSingular3rd : ['Undertakes']
      presentParticiple : ['Undertaking']
    ,
      base : ['Upset']
      pastSimple : ['Upset']
      pastParticiple : ['Upset']
      personSingular3rd : ['Upsets']
      presentParticiple : ['Upsetting']
    ,
      base : ['Vex']
      pastSimple : ['Vext/Vexed']
      pastParticiple : ['Vext/Vexed']
      personSingular3rd : ['Vexes']
      presentParticiple : ['Vexing']
    ,
      base : ['Wake']
      pastSimple : ['Woke']
      pastParticiple : ['Woken']
      personSingular3rd : ['Wakes']
      presentParticiple : ['Waking']
    ,
      base : ['Wear']
      pastSimple : ['Wore']
      pastParticiple : ['Worn']
      personSingular3rd : ['Wears']
      presentParticiple : ['Wearing']
    ,
      base : ['Weave']
      pastSimple : ['Wove']
      pastParticiple : ['Woven']
      personSingular3rd : ['Weaves']
      presentParticiple : ['Weaving']
    ,
      base : ['Wed']
      pastSimple : ['Wed/Wedded']
      pastParticiple : ['Wed/Wedded']
      personSingular3rd : ['Weds']
      presentParticiple : ['Wedding']
    ,
      base : ['Weep']
      pastSimple : ['Wept']
      pastParticiple : ['Wept']
      personSingular3rd : ['Weeps']
      presentParticiple : ['Weeping']
    ,
      base : ['Wend']
      pastSimple : ['Wended/Went']
      pastParticiple : ['Wended/Went']
      personSingular3rd : ['Wends']
      presentParticiple : ['Wending']
    ,
      base : ['Wet']
      pastSimple : ['Wet/Wetted']
      pastParticiple : ['Wet/Wetted']
      personSingular3rd : ['Wets']
      presentParticiple : ['Wetting']
    ,
      base : ['Win']
      pastSimple : ['Won']
      pastParticiple : ['Won']
      personSingular3rd : ['Wins']
      presentParticiple : ['Winning']
    ,
      base : ['Wind']
      pastSimple : ['Wound']
      pastParticiple : ['Wound']
      personSingular3rd : ['Winds']
      presentParticiple : ['Winding']
    ,
      base : ['Withdraw']
      pastSimple : ['Withdrew']
      pastParticiple : ['Withdrawn']
      personSingular3rd : ['Withdraws']
      presentParticiple : ['Withdrawing']
    ,
      base : ['Withhold']
      pastSimple : ['Withheld']
      pastParticiple : ['Withheld']
      personSingular3rd : ['Withholds']
      presentParticiple : ['Withholding']
    ,
      base : ['Withstand']
      pastSimple : ['Withstood']
      pastParticiple : ['Withstood']
      personSingular3rd : ['Withstands']
      presentParticiple : ['Withstanding']
    ,
      base : ['Wring']
      pastSimple : ['Wrung']
      pastParticiple : ['Wrung']
      personSingular3rd : ['Wrings']
      presentParticiple : ['Wringing']
    ,
      base : ['Write']
      pastSimple : ['Wrote']
      pastParticiple : ['Written']
      personSingular3rd : ['Writes']
      presentParticiple : ['Writing']
    ,
      base : ['Zinc']
      pastSimple : ['Zinced/Zincked']
      pastParticiple : ['Zinced/Zincked']
      personSingular3rd : ['Zincs']
      presentParticiple : ['Zincking']
    ]
    irregularVerb.forEach (el)->
      IrregularVerb.insert(el)
  # code to run on server at startup

  return